### ISSUE TITLE
Add tests and documentations for Milestone 3

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/ggexpress#40]
- [x] Add adequate integration tests

- [x] Add additional test cases, if required

- [x] examine docstrings of your functions

- [x] examine whether one-line descriptions of your unit test functions make sense
